### ISSUE TITLE
JGras-FuzzyHashing.linux-x86_64.so: undefined symbol

### ISSUE THREAD

**Issue by GTrunSec** [J-Gras/zeek-fuzzy-hashing#2]
Testing Environment 
- Bro: 2.6.1
- tlsh mast branch
- Lib  libtlsh-dev libfuzzy-dev (Debian 9)

Debugging output
` new file, F9an0X3XKSA4babIFj
bro: symbol lookup error: /usr/local/bro/lib/bro/plugins/JGras_FuzzyHashing//lib/JGras-FuzzyHashing.linux-x86_64.so: undefined symbol: _ZN4Tlsh5finalEPKhji`

ldd - 

`ldd -r JGras-FuzzyHashing.linux-x86_64.so
	linux-vdso.so.1 (0x00007ffd4c5d4000)
	libfuzzy.so.2 => /usr/local/lib/libfuzzy.so.2 (0x00007f01f3140000)
	libtlsh.so.0 => /usr/lib/x86_64-linux-gnu/libtlsh.so.0 (0x00007f01f2f0c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f01f2d89000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f01f2c06000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f01f2bec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01f2a2b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f01f3156000)
undefined symbol: _ZTIN6plugin6PluginE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin13InitPreScriptEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin14InitPostScriptEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin4DoneEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin12HookLoadFileENS0_8LoadTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin16HookCallFunctionEPK4FuncP5FrameP8ValPList	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin14HookQueueEventEP5Event	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin15HookDrainEventsEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin21HookUpdateNetworkTimeEd	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin21HookSetupAnalyzerTreeEP10Connection	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin14HookBroObjDtorEPv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin11HookLogInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_bbRKN7logging13WriterBackend10WriterInfoEiPKPKN9threading5FieldE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin12HookLogWriteERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_RKN7logging13WriterBackend10WriterInfoEiPKPKN9threading5FieldEPPNSE_5ValueE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin12HookReporterERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE15EventHandlerPtrPK10ConnectionPK8ValPListbPK8LocationSI_bS8_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin11MetaHookPreENS_8HookTypeERKNSt7__cxx114listINS_12HookArgumentESaIS4_EEE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin12MetaHookPostENS_8HookTypeERKNSt7__cxx114listINS_12HookArgumentESaIS4_EEES4_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTIN13file_analysis8AnalyzerE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTI7HashVal	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK7HashVal13GetSerialTypeEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK7HashVal11DoSerializeEP10SerialInfo	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal13DoUnserializeEP12UnserialInfo	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val8DescribeEP5ODesc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6BroObj15SetLocationInfoEPK8LocationS2_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6BroObj21UpdateLocationEndInfoERK8Location	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val5CloneEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val7SizeValEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val16MemoryAllocationEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val5AddToEPS_i	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val10RemoveFromEPS_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val12DescribeReSTEP5ODesc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val11ValDescribeEP5ODesc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK3Val15ValDescribeReSTEP5ODesc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK7HashVal7IsValidEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal4InitEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal4FeedEPKvm	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal3GetEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal6DoInitEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal6DoFeedEPKvm	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal5DoGetEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTV3Val	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: file_mgr	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTV7HashVal	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: timer_mgr	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN11TransientID7counterE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: mgr	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: reporter	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN13file_analysis8Analyzer10id_counterE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: end_location	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTVN13file_analysis8AnalyzerE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: start_location	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: bro_version_2_6_1_plugin_6	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZTV6BroObj	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN11BuiltinFuncC1EPFP3ValP5FrameP8ValPListEPKci	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin10AddBifItemERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7BifItem4TypeE(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN13file_analysis8AnalyzerD2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z7bad_refi	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN3TagC2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin7Manager15RegisterBifFileEPKcPFvPNS_6PluginEE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z9type_name7TypeTag	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN13file_analysis9ComponentC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPFPNS_8AnalyzerEP9RecordValPNS_4FileEEj	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z11delete_valsP8ValPList	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6BroObj15SetLocationInfoEPK8LocationS2_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN4Tlsh5finalEPKhji	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6PluginC2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN8BaseList6appendEPv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN9StringValC1EPKc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashValC2EP10OpaqueType	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN3TagC2ERKS_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN10OpaqueTypeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN8EventMgr10QueueEventEP5Event	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z8to_upperRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN8BaseListC2Ei	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK12EventHandlercvbEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN9OpaqueValD2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN8Reporter5ErrorEPKcz	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN3TagD2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6Plugin12AddComponentEPNS_9ComponentE	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z16base_type_no_ref7TypeTag	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN7HashVal4InitEv	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _Z16internal_handlerPKc	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6BroObjD2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN5EventC1E15EventHandlerPtrP8ValPListmjP8TimerMgrP6BroObj	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZNK6BroObj6BadTagEPKcS1_S1_	(./JGras-FuzzyHashing.linux-x86_64.so)
undefined symbol: _ZN6plugin6PluginD2Ev	(./JGras-FuzzyHashing.linux-x86_64.so)`

**Comment by J-Gras** [comment]
I haven't tested the plugin with Bro 2.6 so far but I will have a look. Just to make sure: Did you rebuild the plugin after switching to 2.6.1?

**Comment by GTrunSec** [comment]
> I haven't tested the plugin with Bro 2.6 so far but I will have a look. Just to make sure: Did you rebuild the plugin after switching to 2.6.1?


Sure. But I thought, My problem from the wrong installing way. I would write the install commands line like this. :

```
mkdir ~/src/fuzzy-hash

cd ~/src/fuzzy-hash

git clone https://github.com/ssdeep-project/ssdeep.git

cd ssdeep

./bootstrap

./configure

make

sudo make install

sudo apt-get install libtlsh-dev libfuzzy-dev

cd ~/src/fuzzy-hash

git clone https://github.com/trendmicro/tlsh.git

cd tlsh

./make.sh

cd build

cd release

make

sudo make install

cd ~/src/fuzzy-hash

git clone https://github.com/J-Gras/bro-fuzzy-hashing.git

cd bro-fuzzy-hashing

mkdir tlsh

cp -r ~/src/fuzzy-hash/tlsh/include/* tlsh/.

./configure --bro-dist=../../bro-2.6.1
make

sudo make install 
```
This is configured info. It looks like nothing incorrect
```

-- Bro executable      : /home/gtrun/src/software/bro-2.6.1/build/src/bro
-- Bro source          : /home/gtrun/src/software/bro-2.6.1
-- Bro build           : /home/gtrun/src/software/bro-2.6.1/build
-- Bro install prefix  : /usr/local/bro
-- Bro plugin directory: /usr/local/bro/lib/bro/plugins
-- Bro debug mode      : false
-- Found SSDeep: /usr/local/lib/libfuzzy.so
-- Found TLSH: /usr/lib/x86_64-linux-gnu/libtlsh.so
-- Libfuzzy (ssdeep) header prefix  : /usr/local/include
-- Libfuzzy (ssdeep) library path   : /usr/local/lib/libfuzzy.so
-- TLSH header prefix               : /usr/local/include
-- TLSH library path                : /usr/lib/x86_64-linux-gnu/libtlsh.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gtrun/src/fuzzy-hash/bro-fuzzy-hashing/build

```

**Comment by GTrunSec** [comment]
Sorry about that. I found the problem.  The libtlsh-dev of Debian has a symbolic link error of tlsh-library. That made the problem happened.
